import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { MainCategories } from 'src/modules/categories/main_categories.entity';
import { SubCategories } from 'src/modules/categories/sub_categories.entity';
import { Product } from 'src/modules/products/products.entity';
import { Repository } from 'typeorm';
import { IProductSeed, ISeeder } from '../seeder.interface';
import { seederRunner } from '../shared';

@Injectable()
export default class ProductSeed implements ISeeder {
  private productsData: IProductSeed[] = [
    {
      name: 'HP Elitebook 1030 G2',
      image: 'laptop.jpeg',
      price: 100,
      brand: 'HP',
      availability: 10,
      colors: ['#C0C0C0', '#000000'],
      category: 'Gadgets',
      subCategory: 'Laptops',
      attributes: {
        storage: '512GB SSD',
        ram: '16GB RAM',
        processor: '2.5GHz Intel Core-i5',
        display: '14 inch',
        operating_system: 'Windows',
        wifi: 'Yes',
        bluetooth: 'Yes',
        webcam: 'Yes',
        battery: '4 - 5 hours',
      },
      type: 'computer',
      reviews: [],
      shortDescription: '',
      originalPrice: 100,
      discount: 0,
    },
    {
      name: 'HP Elitebook 1030 G2 2',
      image: 'laptop.jpeg',
      price: 100,
      brand: 'Apple',
      availability: 10,
      colors: ['#C0C0C0', '#000000'],
      category: 'Gadgets',
      subCategory: 'Laptops',
      attributes: {
        storage: '512GB SSD',
        ram: '16GB RAM',
        processor: '2.5GHz Intel Core-i5',
        display: '14 inch',
        operating_system: 'Windows',
        wifi: 'Yes',
        bluetooth: 'Yes',
        webcam: 'Yes',
        battery: '4 - 5 hours',
      },
      type: 'computer',
      reviews: [],
      shortDescription: '',
      originalPrice: 100,
      discount: 0,
    },
    {
      name: 'Iphone 14 Pro Max',
      image: 'phone.jpeg',
      price: 800000,
      brand: 'Apple',
      availability: 10,
      colors: ['#C0C0C0', '#000000'],
      category: 'Gadgets',
      subCategory: 'Phones',
      attributes: {
        storage: '512GB',
        ram: '6GB',
        display: '6.1 inch',
        battery: '3200mAh',
        camera: '48 MP',
      },
      type: 'phone',
      reviews: [],
      shortDescription: '',
      originalPrice: 100,
      discount: 0,
    },
    {
      name: 'Samsung Tab',
      image: 'tablet.jpeg',
      price: 800000,
      brand: 'Samsung',
      availability: 10,
      colors: ['#C0C0C0', '#000000'],
      category: 'Gadgets',
      subCategory: 'Tablets',
      attributes: {
        storage: '512GB',
        ram: '6GB',
        display: '6.1 inch',
        battery: '3200mAh',
        camera: '48 MP',
      },
      type: 'phone',
      reviews: [],
      shortDescription: '',
      originalPrice: 100,
      discount: 0,
    },
    {
      name: 'HP Elitebook 1030 G2 1',
      image: 'desktop.jpeg',
      price: 800000,
      brand: 'HP',
      availability: 10,
      colors: ['#C0C0C0', '#000000'],
      category: 'Gadgets',
      subCategory: 'Desktops',
      attributes: {
        storage: '512GB',
        ram: '16GB RAM',
        processor: '2.5GHz Intel Core-i5',
        display: '14-inch',
        operatingSystem: 'Windows',
        wifi: 'Yes',
        bluetooth: 'Yes',
        webcam: 'Yes',
        battery: 'N/A',
      },
      type: 'computer',
      reviews: [],
      shortDescription: '',
      originalPrice: 100,
      discount: 0,
    },
    {
      name: 'HP',
      image: 'printer.jpeg',
      price: 800000,
      brand: 'HP',
      availability: 10,
      colors: ['#C0C0C0', '#000000'],
      category: 'Gadgets',
      subCategory: 'Printers',
      attributes: {
        mobile_device_printing: 'Yes',
        networking: 'Wireless',
        energy_star_certified: 'Yes',
        printer_type: 'All In One',
        ISO_color_print_speed: '5 pages per minute',
        ISO_mono_print_speed: '12 pages per minute',
        output_tray_capacity: '30',
        touch_screen: 'No',
      },
      type: 'printer',
      reviews: [],
      shortDescription: '',
      originalPrice: 100,
      discount: 0,
    },
    {
      name: 'JBL Flip 5',
      image: 'speakers.jpeg',
      price: 800000,
      brand: 'JBL',
      availability: 10,
      colors: ['#C0C0C0', '#000000'],
      category: 'Gadgets',
      subCategory: 'Speakers',
      attributes: {
        waterproof: 'Yes',
        noise_cancellation: 'Yes',
        sound_output: '30 Watts',
        max_play_time: '20 hours',
        charge_time: '2 hours',
        bluetooth: 'Yes',
        'aux_in_(3.5)': 'Yes',
        'wireless_party_link_(Dual_Mode)': 'Yes',
        'wireless_party_link_(Multi_Mode)': 'Yes',
        speaker_phone: 'Yes',
        'power_output_THD_10%': '1250W (Only Bypass Condition Measure)',
        'sub-woofer_L/R': '200/200',
        USB: '1',
        'audio_input_(Optical)': '1',
        'bluetooth_(Rx_/_Tx)': 'Yes',
      },
      type: 'speaker',
      reviews: [],
      shortDescription: '',
      originalPrice: 100,
      discount: 0,
    },
    {
      name: 'Hisense',
      image: 'refrigerator.jpeg',
      price: 800000,
      brand: 'Hisense',
      availability: 10,
      colors: ['#C0C0C0', '#000000'],
      category: 'Electronics',
      subCategory: 'Refrigerator',
      attributes: {
        capacity: '541 Litre',
        no_frost: 'Yes',
        low_noise: 'Yes',
        environment_friendly_tech: 'Yes',
        'dimensions_(W_X_D_X_H)': '(W X D X H) 912 X 725 X 1785 (Mm)',
      },
      type: 'fridge',
      reviews: [],
      shortDescription: '',
      originalPrice: 100,
      discount: 0,
    },
    {
      name: 'Hisense 1',
      image: 'freezer.jpeg',
      price: 800000,
      brand: 'Hisense',
      availability: 10,
      colors: ['#C0C0C0', '#000000'],
      category: 'Electronics',
      subCategory: 'Freezer',
      attributes: {
        size: '420L',
        power_indicator_function: 'Yes',
        gas_type: 'R600',
        doors: '1',
      },
      type: 'freezer',
      reviews: [],
      shortDescription: '',
      originalPrice: 100,
      discount: 0,
    },
    {
      name: 'Hisense 2',
      image: 'microwave.jpeg',
      price: 800000,
      brand: 'Hisense',
      availability: 10,
      colors: ['#C0C0C0', '#000000'],
      category: 'Electronics',
      subCategory: 'Microwave',
      attributes: {
        capacity: '20L',
        control_type: 'digital',
        open_type: 'Push Button',
        child_safety_lock: 'Yes',
        door_glass: 'black',
        power_levels: '11',
        timer: '99:99 Min',
        dimensions: '440 X 328 X 29 Mm',
      },
      type: 'microwave',
      reviews: [],
      shortDescription: '',
      originalPrice: 100,
      discount: 0,
    },
    {
      name: 'Hisense 3',
      image: 'cooker.jpeg',
      price: 800000,
      brand: 'Hisense',
      availability: 10,
      colors: ['#C0C0C0', '#000000'],
      category: 'Electronics',
      subCategory: 'Cooker',
      attributes: {
        burners: '5',
        ignition_button: 'Yes',
        oven_burner: 'Up And Down',
        tray_and_wire_grid: 'Yes',
        oven_glass: 'double',
        oven_lamp: 'Yes',
        'dimensions_(H*W*D)': '88*89*83 Cm',
      },
      type: 'cooker',
      reviews: [],
      shortDescription: '',
      originalPrice: 100,
      discount: 0,
    },
    {
      name: 'Hisense 4',
      image: 'washing_machine.jpeg',
      price: 800000,
      brand: 'Hisense',
      availability: 10,
      colors: ['#C0C0C0', '#000000'],
      category: 'Electronics',
      subCategory: 'Washing machine',
      attributes: {
        water_selector: 'Yes',
        washing_selector: 'Gentle, Normal, Strong',
        'dimensions_(W_X_H_X_D)_(Mm)': '700x900x430_Mm',
        'wash_capacity_(Kg)': '8 Kg',
        pulsator: 'Punch+3',
        key_USP2: 'Smart Inverter',
        turbo_drum: 'Yes',
        'multi-Clean_filter': 'Yes',
        capacity: '7.5 KG',
        direct_drive_motor: 'Yes',
        type: 'Front loader/Full Automatic Washer Only',
      },
      type: 'washing_machine',
      reviews: [],
      shortDescription: '',
      originalPrice: 100,
      discount: 0,
    },
    {
      name: 'Hisense 5',
      image: '',
      price: 800000,
      brand: 'Hisense',
      availability: 10,
      colors: ['#C0C0C0', '#000000'],
      category: 'Electronics',
      subCategory: 'Dryer',
      attributes: {
        'drying_capacity_(L)': '8 Kg',
        'spin_speed_(Rpm)': '51±3',
        'noise_level_DB(A)': '68',
        display: 'LED',
        number_of_programs: '15',
        'unit_dimension_(W*H*D)Mm': '595*850*555',
      },
      type: 'dryer',
      reviews: [],
      shortDescription: '',
      originalPrice: 100,
      discount: 0,
    },
    {
      name: 'Maxi',
      image: 'water_dispenser.jpeg',
      price: 800000,
      brand: 'Maxi',
      availability: 10,
      colors: ['#C0C0C0', '#000000'],
      category: 'Electronics',
      subCategory: 'Water dispenser',
      attributes: {
        '2_FAUCETS': '(HOT, COLD)',
        child_lock: 'Yes',
        refrigerator: '20 L',
        hot_water: '4L/H',
        cold_water: '2L/H',
        ratted_power: '570 Watt',
      },
      type: 'water_dispenser',
      reviews: [],
      shortDescription: '',
      originalPrice: 100,
      discount: 0,
    },
    {
      name: 'Maxi 1',
      image: 'generator.jpeg',
      price: 800000,
      brand: 'Maxi',
      availability: 10,
      colors: ['#C0C0C0', '#000000'],
      category: 'Electronics',
      subCategory: 'Generator',
      attributes: {
        power: '8.0 KW / 10 KVA',
        operate: 'Manual And Keys',
        coil: 'Copper',
        battery: 'included',
        noise_reduction: 'Yes',
        tank: '25L (9 Hours Full Loaad)',
        AVR_voltage_regulator: 'Yes',
        portable: 'Yes',
        engine_oil_alert: 'Yes',
        'gross_weight_(KG)': '105 KG',
        'net_weight_(KG)': '99 KG',
        'dimensions_(L_X_W_X_H)_(Mm)': '720 X 540 X 600',
      },
      type: 'generator',
      reviews: [],
      shortDescription: '',
      originalPrice: 100,
      discount: 0,
    },
    {
      name: 'Maxi 2',
      image: '',
      price: 800000,
      brand: 'Maxi',
      availability: 10,
      colors: ['#C0C0C0', '#000000'],
      category: 'Electronics',
      subCategory: 'Water heater',
      attributes: {
        rated_capacity: '10 L',
        rated_power: '2000W',
        rated_frequency: '50Hz',
        rated_pressure: '0.75 MPa',
        rated_voltage: '220 - 240 V',
        max_temp: '105',
        'measurements_(Mm)': '324 * 324 * 315',
      },
      type: 'water_heater',
      reviews: [],
      shortDescription: '',
      originalPrice: 100,
      discount: 0,
    },
    {
      name: 'Hisense 7',
      image: '',
      price: 800000,
      brand: 'Hisense',
      availability: 10,
      colors: ['#C0C0C0', '#000000'],
      category: 'Electronics',
      subCategory: 'Air purifier',
      attributes: {
        'net_dimensions_W_X_H_X_D_(Mm)': '338 X 723 X 510',
        core_indicators: '4',
        indicator:
          'CADR(M3/H), CCM(Mg), CCE(M3/Kwh), Noise(DB) 260, P2, 5, Low Noise',
        purify: '18~31m2',
        filter_steps: '3',
        high_density_filter: 'Hair And Big Dust',
        HEPA_filter: 'PM2.5, Smoke, Mites, Pollen, Small Dust',
        timing_function: 'Yes',
        child_lock: 'Yes',
      },
      type: 'air_purifier',
      reviews: [],
      shortDescription: '',
      originalPrice: 100,
      discount: 0,
    },
    {
      name: 'LG',
      image: '',
      price: 800000,
      brand: 'LG',
      availability: 10,
      colors: ['#C0C0C0', '#000000'],
      category: 'Electronics',
      subCategory: 'Dishwasher',
      attributes: {
        type: 'QuadWASH™&Trade',
        smart_function: 'SmartThin™Q&Trade',
        energy: 'A++',
        tub_material: 'NeveRust™ Stainless Steel',
        capacity: '14 Place Settings',
      },
      type: 'dishwasher',
      reviews: [],
      shortDescription: '',
      originalPrice: 100,
      discount: 0,
    },
    {
      name: 'LG 1',
      image: '',
      price: 800000,
      brand: 'LG',
      availability: 10,
      colors: ['#C0C0C0', '#000000'],
      category: 'Electronics',
      subCategory: 'TV',
      attributes: {
        diagonal: '65 inches',
        resolution: '4K • 3840 X 2160',
        aspect_ratio: '16:9',
        pixel_density: '103 Ppi',
        panel_type: 'LCD',
        LCD_technology: 'IPS',
        backlight_type: 'LED',
        quantum_dots: 'No',
        HDMI: 'Yes (3)',
        USB: 'Yes (1)',
      },
      type: 'tv',
      reviews: [],
      shortDescription: '',
      originalPrice: 100,
      discount: 0,
    },
    {
      name: 'LG 2',
      image: 'mini_hifi_system.jpeg',
      price: 800000,
      brand: 'LG',
      availability: 10,
      colors: ['#C0C0C0', '#000000'],
      category: 'Electronics',
      subCategory: 'Mini hifi system',
      attributes: {
        'power_output_-_front': '1250W X 2',
        'power_output_-_sub_woofer': '1250W X 2',
        'power_requirement_-_narrow_(50/60Hz)': '110 Or 220/230V 50/60Hz',
        echo_mode: 'Yes',
        vocal_effects: 'Yes',
      },
      type: 'mini_hifi_system',
      reviews: [],
      shortDescription: '',
      originalPrice: 100,
      discount: 0,
    },
    {
      name: 'Hisense 8',
      image: 'soundbar.jpeg',
      price: 800000,
      brand: 'Hisense',
      availability: 10,
      colors: ['#C0C0C0', '#000000'],
      category: 'Electronics',
      subCategory: 'Sound bar',
      attributes: {
        soundbar_dimensions: '36.2 X 2.4 X 3.5 Inches',
        soundbar_weight: '2.54 Kg',
        subwoofer_dimensions: '8.4 X 11.6 X 12 Inches',
        package_dimensions: '39.37 X 17.87 X 9.33inches',
        subwoofer: 'Wireless Subwoofer',
        sound_mode: 'Movie/Music/News/Night/Sport/Game/AI Mode',
        display_screen: 'Yes, LED Screen',
        power_consumption: 'Soundbar: 20W | Subwoofer: 15W',
      },
      type: 'sound_bar',
      reviews: [],
      shortDescription: '',
      originalPrice: 100,
      discount: 0,
    },
    {
      name: 'Hisense 9',
      image: 'dvd_player.jpeg',
      price: 800000,
      brand: 'Hisense',
      availability: 10,
      colors: ['#C0C0C0', '#000000'],
      category: 'Electronics',
      subCategory: 'Dvd player',
      attributes: {
        video_DAC: '108MHz/14bit',
        'IN/OUT': 'HDMI Output',
        convenience: '1080p Upscaling',
        accessories: 'Remote Control',
        DTS_digital_out: 'Yes',
      },
      type: 'dvd_player',
      reviews: [],
      shortDescription: '',
      originalPrice: 100,
      discount: 0,
    },
    {
      name: 'LG 3',
      image: '',
      price: 800000,
      brand: 'LG',
      availability: 10,
      colors: ['#C0C0C0', '#000000'],
      category: 'Electronics',
      subCategory: 'AV Receiver System',
      attributes: {
        USB_jack: 'Yes',
        bluetooth: 'Yes',
        bluetooth_remote_app: 'Yes',
        'bass_blast_(BASS)': 'Yes',
        DJ_effect: 'Yes',
        sound_effect_dolby_digital: 'Yes',
        'power_output_(THD_20%)_total': '2300W',
        'power_output_(THD_20%)_front': '460 X 2',
        'power_output_(THD_20%)_subwoofer': '230 X 2',
        function_aux: '2',
        'function_FM/AM/RDS': 'FM',
      },
      type: 'av_receiver_system',
      reviews: [],
      shortDescription: '',
      originalPrice: 100,
      discount: 0,
    },
    {
      name: 'LG 4',
      image: 'air_conditioner.jpeg',
      price: 800000,
      brand: 'LG',
      availability: 10,
      colors: ['#C0C0C0', '#000000'],
      category: 'Electronics',
      subCategory: 'A/C',
      attributes: {
        capacity_cooling_rated_w: '2,374',
        power_input_cooling_rated_w: '913',
        running_current_cooling_rated_a: '4.3',
        power_supply: '1P, 220-240V, 50Hz',
        exterior_color_code: 'white',
        'moisture_removal_I/H': '1.0',
        outdoor_fan_motor_speed: '850',
        'indoor_dimensions_(W_X_H_X_D)': '76.2 X 25.5 X 19',
        'indoor_weight_(Kg)': '8.5',
        outdoor_dimensions: '76.5 X 47.8 X 31',
        'outdoor_weight_(Kg)': '25',
        air_flow: '10 Meters',
        cooling: 'Super Cooling',
        gold_fin: 'Yes',
        'net_dimensions_W_X_H_X_D_(Mm)': '430*695*325',
        'packing_dimensions_W_X_H_X_D_(Mm)': '480*880*380',
        'net_weight_(Kg)': '27',
        'shipping_weight_(Kg)': '32',
        'cooling_/_heating_capacity': '3200 W / 2800 W',
        'input_cooling_/_heating_power': '1032 W / 933 W',
        refrigerant: 'R410a, 490g',
      },
      type: 'a/c',
      reviews: [],
      shortDescription: '',
      originalPrice: 100,
      discount: 0,
    },
    {
      name: 'PlayStation 5',
      image: '',
      price: 800000,
      brand: 'Sony',
      availability: 10,
      colors: ['#C0C0C0', '#000000'],
      category: 'Gadgets',
      subCategory: 'Games',
      attributes: {
        console_type: 'Home Console',
        input_method: 'Disc',
        hard_disk: '825GB PCie Gen 4 NVMe SSD',
        RAM: '16GB GDDR6',
        processor:
          'Custom 8-core AMD Zen 2 CPU @ 3.5GHz with SMT (variable frequency)',
        graphics: 'Custom AMD RDNA 2 GPU 36 CUs @ 2.23GHz (variable frequency)',
        ethernet: 'Gigabit',
        weight: '4.5kg',
        HDMI: '1',
        USB: '4',
        'Wi-Fi': 'Wi-Fi 6 802.11ax',
      },
      type: 'playstation',
      reviews: [],
      shortDescription: '',
      originalPrice: 100,
      discount: 0,
    },
    {
      name: 'Brand New Apple IPhone XS Max ( 256GB ROM + 4GB RAM) IOS 12 (12MP + 12MP)+7MP-Water Resistant',
      image:
        'https://sonik360.com/wp-content/uploads/2020/08/1464AA0C-34DC-487A-AE75-5E8C9C4679C4.png, https://sonik360.com/wp-content/uploads/2020/08/0137E238-0441-4E8B-893B-90FE936E7EE4.jpeg, https://sonik360.com/wp-content/uploads/2020/08/999ABBB1-E48C-4C7A-A615-DDB0DB0CB988.jpeg, https://sonik360.com/wp-content/uploads/2020/08/6EDF6FB9-9447-4F0D-B30D-350F179ABE7C.jpeg, https://sonik360.com/wp-content/uploads/2020/08/474FB5CB-9DB4-491A-BF76-593D0D67A380.jpeg',
      price: 800000,
      brand: 'Apple',
      availability: 10,
      colors: ['black', 'gold', 'white'],
      category: 'Gadgets',
      subCategory: 'Phones',
      attributes: {
        ROM: '64',
        RAM: '4GB',
      },
      type: 'phone',
      reviews: [],
      shortDescription:
        '<ul class="a-unordered-list a-vertical a-spacing-none"><li style="text-align: center;" data-mce-style="text-align: center;">H6.5-inch Super Retina display (OLED) with HDR</li><li>IP68 dust and water resistant (maximum depth of 2 meters up to 30 minutes)</li><li>12MP dual cameras with dual OIS and 7MP TrueDepth front camera—Portrait mode, Portrait Lighting, Depth Control, and Smart HDR</li><li>Face ID for secure authentication</li><li>A12 Bionic with next-generation Neural Engine</li><li>Wireless charging—works with Qi chargers</li><li>iOS 12 with Memoji, Screen Time, Siri Shortcuts, and Group FaceTime</li></ul>',
      originalPrice: 800000,
      discount: 0,
    },
  ];

  constructor(
    @InjectRepository(Product) private productRepo: Repository<Product>,
    @InjectRepository(MainCategories)
    private mainCategoryRepo: Repository<MainCategories>,
    @InjectRepository(SubCategories)
    private subCategoryRepo: Repository<SubCategories>,
  ) {}

  async run(): Promise<boolean> {
    return seederRunner(
      this.productsData,
      this.productRepo,
      this.mainCategoryRepo,
      this.subCategoryRepo,
    );
  }
}
